#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

autorandr --change
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d DP2-2 1 2 3
bspc monitor -d DP1 1 2 3

bspc config border_width        0
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

dunst &
picom --daemon
~/.fehbg
